"""add_template_field

Revision ID: add_template_field
Revises: add_custom_intervals
Create Date: 2025-05-14 14:46:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_template_field'
down_revision = 'add_custom_intervals'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('template', sa.String(), nullable=True, server_default='lkr'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'template')
    # ### end Alembic commands ###
